const chinese_recipe = {
  "code": "0",
  "list": [
    {
      "createTime"       : 1583828004000,
      "creatorId"        : "0",
      "creatorType"      : "ADM",
      "dosageForm"       : "饮片",
      "dosageUnit"       : "g",
      "drugAdmission"    : "煎服",
      "drugCode"         : "1050032",
      "drugName"         : "三七粉",
      "drugOrigin"       : "山东东阿国胶堂阿胶药业有限公司",
      "drugSpecification": "G",
      "drugType"         : "HERBAL_MEDICINE",
      "drugUnit"         : "克",
      "hasInventory"     : true,
      "hosId"            : "3102990001",
      "id"               : "5e674c24ab150937fe0b766b",
      "inventory"        : 2147483622,
      "modifierId"       : "0",
      "modifierType"     : "ADM",
      "modifyTime"       : 1584602399000,
      "price"            : 400,
      "speedyCodePinyin" : "SQF"
    },
    {
      "createTime"       : 1583828004000,
      "creatorId"        : "0",
      "creatorType"      : "ADM",
      "dosageForm"       : "饮片",
      "dosageUnit"       : "g",
      "drugAdmission"    : "煎服",
      "drugCode"         : "1050032",
      "drugName"         : "三七粉2",
      "drugOrigin"       : "山东东阿国胶堂阿胶药业有限公司",
      "drugSpecification": "G",
      "drugType"         : "HERBAL_MEDICINE",
      "drugUnit"         : "克",
      "hasInventory"     : true,
      "hosId"            : "3102990001",
      "id"               : "5e674c24ab150937fe0b766b2",
      "inventory"        : 2147483622,
      "modifierId"       : "0",
      "modifierType"     : "ADM",
      "modifyTime"       : 1584602399000,
      "price"            : 400,
      "speedyCodePinyin" : "SQF"
    },
    {
      "createTime"       : 1583828004000,
      "creatorId"        : "0",
      "creatorType"      : "ADM",
      "dosageForm"       : "饮片",
      "dosageUnit"       : "g",
      "drugAdmission"    : "煎服",
      "drugCode"         : "1050032",
      "drugName"         : "三七粉3",
      "drugOrigin"       : "山东东阿国胶堂阿胶药业有限公司",
      "drugSpecification": "G",
      "drugType"         : "HERBAL_MEDICINE",
      "drugUnit"         : "克",
      "hasInventory"     : true,
      "hosId"            : "3102990001",
      "id"               : "5e674c24ab150937fe0b766b3",
      "inventory"        : 2147483622,
      "modifierId"       : "0",
      "modifierType"     : "ADM",
      "modifyTime"       : 1584602399000,
      "price"            : 400,
      "speedyCodePinyin" : "SQF"
    },
    {
      "createTime"       : 1583828004000,
      "creatorId"        : "0",
      "creatorType"      : "ADM",
      "dosageForm"       : "饮片",
      "dosageUnit"       : "g",
      "drugAdmission"    : "煎服",
      "drugCode"         : "1050032",
      "drugName"         : "三七粉4",
      "drugOrigin"       : "山东东阿国胶堂阿胶药业有限公司",
      "drugSpecification": "G",
      "drugType"         : "HERBAL_MEDICINE",
      "drugUnit"         : "克",
      "hasInventory"     : true,
      "hosId"            : "3102990001",
      "id"               : "5e674c24ab150937fe0b766b4",
      "inventory"        : 2147483622,
      "modifierId"       : "0",
      "modifierType"     : "ADM",
      "modifyTime"       : 1584602399000,
      "price"            : 400,
      "speedyCodePinyin" : "SQF"
    }
  ],
  "page": {
    "pageNum" : 1,
    "pageSize": 200,
    "pages"   : 1,
    "total"   : 1
  },
  "succ": true
}

export default chinese_recipe
