const west_recipe = {
  'code': '0',
  'list': [
    {
      'createTime'       : 1583890169000,
      'creatorId'        : '0',
      'creatorType'      : 'ADM',
      'description'      : '',
      'dosageForm'       : '片剂',
      'dosageUnit'       : '盒',
      'drugAdmission'    : '口服',
      'drugCode'         : 'amxl',
      'drugEnglishName'  : '',
      'drugName'         : '阿莫西林胶囊',
      'drugOrigin'       : '广东',
      'drugSpecification': 'g',
      'drugType'         : 'PATENT_MEDICINE',
      'drugUnit'         : 'g',
      'hasInventory'     : true,
      'hosId'            : '3102990001',
      'id'               : '5e683ef8ab15e784a318882c',
      'inventory'        : 2147483645,
      'modifierId'       : '0',
      'modifierType'     : 'ADM',
      'modifyTime'       : 1584089609000,
      'price'            : 12,
      'speedyCodeOther'  : '',
      'speedyCodePinyin' : 'amxl',
      'speedyCodeWubi'   : 'amxl'
    }, {
      'createTime'       : 1583819959000,
      'creatorId'        : '0',
      'creatorType'      : 'ADM',
      'description'      : '',
      'dosageForm'       : '饮片',
      'dosageUnit'       : '盒',
      'drugAdmission'    : '注射',
      'drugCode'         : 'TTT',
      'drugEnglishName'  : '',
      'drugName'         : '头孢地尼分散片',
      'drugOrigin'       : '天津市',
      'drugSpecification': 'mg',
      'drugType'         : 'WESTERN_MEDICINE',
      'drugUnit'         : '毫升',
      'hasInventory'     : true,
      'hosId'            : '3102990001',
      'id'               : '5e672cb7ab158e20a884210d',
      'inventory'        : 2147483647,
      'modifierId'       : '0',
      'modifierType'     : 'ADM',
      'modifyTime'       : 1583890920000,
      'price'            : 13,
      'speedyCodeOther'  : '',
      'speedyCodePinyin' : 'TTT',
      'speedyCodeWubi'   : 'dosageUnit'
    }, {
      'createTime'       : 1583819959000,
      'creatorId'        : '0',
      'creatorType'      : 'ADM',
      'description'      : '',
      'dosageForm'       : '饮片',
      'dosageUnit'       : '盒',
      'drugAdmission'    : '注射',
      'drugCode'         : 'TTT',
      'drugEnglishName'  : '',
      'drugName'         : '头孢地尼分散片2',
      'drugOrigin'       : '天津市',
      'drugSpecification': 'mg',
      'drugType'         : 'WESTERN_MEDICINE',
      'drugUnit'         : '毫升',
      'hasInventory'     : true,
      'hosId'            : '3102990001',
      'id'               : '5e672cb7ab158e20a884210d2',
      'inventory'        : 2147483647,
      'modifierId'       : '0',
      'modifierType'     : 'ADM',
      'modifyTime'       : 1583890920000,
      'price'            : 14,
      'speedyCodeOther'  : '',
      'speedyCodePinyin' : 'TTT',
      'speedyCodeWubi'   : 'dosageUnit'
    }, {
      'createTime'       : 1583819959000,
      'creatorId'        : '0',
      'creatorType'      : 'ADM',
      'description'      : '',
      'dosageForm'       : '饮片',
      'dosageUnit'       : '盒',
      'drugAdmission'    : '注射',
      'drugCode'         : 'TTT',
      'drugEnglishName'  : '',
      'drugName'         : '头孢地尼分散片3',
      'drugOrigin'       : '天津市',
      'drugSpecification': 'mg',
      'drugType'         : 'WESTERN_MEDICINE',
      'drugUnit'         : '毫升',
      'hasInventory'     : true,
      'hosId'            : '3102990001',
      'id'               : '5e672cb7ab158e20a884210d3',
      'inventory'        : 2147483647,
      'modifierId'       : '0',
      'modifierType'     : 'ADM',
      'modifyTime'       : 1583890920000,
      'price'            : 15,
      'speedyCodeOther'  : '',
      'speedyCodePinyin' : 'TTT',
      'speedyCodeWubi'   : 'dosageUnit'
    }],
  'page': {
    'pageNum' : 1,
    'pageSize': 200,
    'pages'   : 1,
    'total'   : 2
  },
  'succ': true
}

export default west_recipe
